name: clean_architecture
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  dartz: ^0.9.2
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^3.0.10
  flutter_modular: ^2.0.1
  bloc: ^7.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.3
flutter:
  uses-material-design: true